baseURL = 'https://leicesterhackspace.org.uk'
languageCode = 'en-GB'
title = 'Leicester Hackspace'
theme = 'hackspace-theme'

[params]
siteImage = "/img/hackspace-logo-inverted.svg"
siteFavIcon = "/img/hackspace-logo.svg"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
  [[menus.main.params]]
    icon = 'img/hackspace-logo-inverted.svg'

[[menus.main]]
name = 'About'
pageRef = '/about.html'
weight = 20

[[menus.main]]
name = 'Contacts'
pageRef = '/contacts.html'
weight = 30

[[menus.main]]
name = 'News'
pageRef = '/news.html'
weight = 40

[[menus.main]]
name = 'Membership'
pageRef = '/membership.html'
weight = 50

[[menus.main]]
name = 'Wiki'
url = "http://wiki4.leicesterhackspace.org.uk"
weight = 60

[[menus.main]]
name = 'Diary'
pageRef = '/diary.html'
weight = 70

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
