baseURL = 'https://leicesterhackspace.org.uk'
languageCode = 'en-GB'
title = 'Leicester Hackspace'
theme = 'hackspace-theme'

[[menus.main]]
name = 'hello'
pageRef = '/hello-world.html'
weight = 30

[[menus.main]]
name = 'hello2'
pageRef = '/hello-world.html'
weight = 20

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true