baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'My New Hugo Site'

[params]
paginate = 5

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
