baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'My New Hugo Site'

[params.pagination]
# The number of pages to list in the pagination
pages = 1

# The number of page links on the pagination pages bar to have either side of the current page
adjacentLinks = 2


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
