name = 'Leicester Hackspace Theme'
license = 'MIT'
licenselink = 'https://github.com/leicesterhackspace/leicester-hackspace-web/blob/master/themes/hackspace-theme/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/leicesterhackspace/leicester-hackspace-web'

# If you have a running demo of the theme
#demosite = ''

# Taxonomy terms
tags = ['hackspace', 'news']
features = ['Responsive layout', 'Paginated news page']

# If the theme has multiple authors
authors = [
  {name = 'Jacob Lucas', homepage = 'jacob-lucas.uk'},
  {name = 'Daniel Warren'}
]
